# Generated by Django 3.0.7 on 2020-09-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_image1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('pro_image2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('pro_image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_description', models.CharField(max_length=200)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.CompanyInfo')),
            ],
        ),
    ]
