# Generated by Django 3.0.7 on 2020-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0002_productdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='pro_id',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='cmp_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
