# Generated by Django 3.0.7 on 2020-09-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0003_auto_20200910_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='pro_price',
            field=models.IntegerField(null=True),
        ),
    ]
