# Generated by Django 3.0.7 on 2020-09-16 04:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShoppingApp', '0004_productdetail_pro_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_user_id', models.CharField(max_length=10)),
                ('user_role', models.CharField(max_length=255)),
                ('role_user_name', models.CharField(max_length=255)),
                ('role_user_email', models.CharField(max_length=255)),
                ('role_user_password', models.CharField(max_length=255)),
                ('role_create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
