# Generated by Django 3.0.7 on 2020-09-27 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0006_careercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(default=0)),
                ('cat_category', models.CharField(max_length=255)),
                ('cat_sub', models.CharField(max_length=255)),
                ('cat_create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
