# Generated by Django 3.0.7 on 2020-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0007_category_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='cmp_name',
            new_name='pro_category',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='pro_image1',
            new_name='pro_image',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='pro_image2',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='pro_image3',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='pro_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='pro_sub',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
