# Generated by Django 3.0.7 on 2020-09-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0009_userreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.ProductDetail'),
        ),
    ]
