# Generated by Django 3.0.7 on 2020-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0010_userreviews_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
