# Generated by Django 3.0.7 on 2020-10-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0011_productdetail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='slug',
        ),
    ]
